apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariantSet
metadata:
  name: free5g-smf-regional
spec:
  upstream:
    package:
      repo: https://github.com/nephio-project/free5gc-packages
      name: pkg-example-smf-bp
    revision: v1
  targets:
  - repositories:
      matchExpressions:
      - key: nephio.org/site-type
        operator: In
        values:
        - regional
        - combined
