apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariantSet
metadata:
  name: free5g-upf-edge
spec:
  upstream:
    package:
      repo: https://github.com/nephio-project/free5gc-packages
      name: pkg-example-upf-bp
    revision: v1
  targets:
  - repositories:
      matchLabels:
        nephio.org/site-type: edge
        nephio.org/site-type: combined
